version: "3"
services:
  mysql:
    container_name: "my_sql_database"
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
      # /bin/sh "mysql_dump.sh"

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "4000:3306"
    volumes:
      - "./database/migration.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - app-tier
      - admin-tier

  db_admin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8090:80
    depends_on:
      - mysql
    networks:
      # define your network where all containers are connected to each other
      - admin-tier

  backend:
    build:
      context: backend
      args:
        port: 1234
    container_name: my_backend
    ports:
      - 8080:1234
    environment:
      PORT: 1234
      DBHOST: mysql
      DBPORT: 3306
      DBUSER: root
      DBPASSWORD: root
      DB: my_database_name
    depends_on:
      - mysql
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
  admin-tier:
    driver: bridge
